FROM golang:1.16-alpine

RUN mkdir /app

WORKDIR /app 

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN go get -u github.com/cosmtrek/air

COPY . .

EXPOSE 8080

ENTRYPOINT ["air","-c","air.toml"]