version: "3.9"
services: 
    app:
        container_name: golang-mongo-prod-app
        build: 
            context: .
            dockerfile: Dockerfile.prod
        expose: 
            - "8080"
        env_file:
            - ./config/prod.env
        depends_on: 
            - mongo
        ports: 
            - "8080:8080"    
    mongo:
        image: mongo:4.4.3
        container_name: golang-mongo-prod-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456 
        ports:
            - "27017:27017"                                 