version: "3.9"
services:
  app:
    container_name: golang-echo-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - echo-mongodb-api
  mongo:
    image: mongo:4.4.3
    container_name: golang-echo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    networks:
      - echo-mongodb-api
  mongo-express:
    image: mongo-express:0.54
    container_name: golang-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: golang-echo-db
    networks:
      - echo-mongodb-api

networks:
  echo-mongodb-api:
    name: echo-mongodb-api
    driver: bridge
